### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by Freaky** [myfreeweb/rusty-sandbox#2]
Any chance of pushing a 0.2 crate with the `sandbox_this_process() -> Result` tweak?  I'm using it in https://www.github.com/Freaky/tarssh and I don't want to push a crate while it's depending on a Git repository.

The alternative is a release that proudly logs `[INFO  tarssh] sandbox, enabled: dunno` :)

**Comment by myfreeweb** [comment]
Sure, done.

Interestingly, I lost the 0.1.0 commit, the master was 0.0.0 still…

**Comment by Freaky** [comment]
Thanks :)
